[package]
name = "wrestic"
version = "0.5.0"
authors = ["alvaro17f"]
description = "Restic wrapper in Rust"
homepage = "https://github.com/alvaro17f/wrestic"
repository = "https://github.com/alvaro17f/wrestic"
license = "LGPL-3.0"
edition = "2021"
keywords = ["restic", "wrapper"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
cmd_lib = "1.3.0"
color-print = "0.3.4"
dialoguer = "0.10.4"
indicatif = "0.17.6"
libc = "0.2.147"
regex = "1.9.3"