[package]
name = "restic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
cmd_lib = "1.3.0"
color-print = "0.3.4"
libc = "0.2.147"
