#  You can add as many settings as you want, just make sure the id is unique
#  and remember, if your repository doesn't exist, it will be created
#  and password will be set to the one you provided in RESTIC_PASSWORD

[user]
USER = "yourcomputerusername"

[settings.your_remote_profile]
BACKEND = "b2"
RESTIC_PASSWORD = "yourresticrepopassword"
REPOSITORY = "yourbucketname:yourrepository"
BACKUP_FOLDER = "/home/yourcomputerusername/backupthisfolder"
RESTORE_FOLDER = "/home/yourcomputerusername/restoretothisfolder"
KEEP_LAST = 10

[settings.your_remote_profile.env]
B2_ACCOUNT_ID = "yourbackblazeb2accountid"
B2_ACCOUNT_KEY = "yourbackblazeb2accountkey"


[settings.your_local_profile]
BACKEND = "local"
RESTIC_PASSWORD = "yourlocalresticrepopassword"
REPOSITORY = "yourlocalrepository"
BACKUP_FOLDER = "/home/yourcomputerusername/backupthisotherfolder"
RESTORE_FOLDER = "/home/yourcomputerusername/restoretothisotherfolder"
KEEP_LAST = 8
